version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./videos:/app/videos
      - ./thumbnails:/app/thumbnails
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
            - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
